name: Github Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  test_schedule:
    name: Run the application
    runs-on: ubuntu-latest
    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo pip install -r requirements.txt
    - name: Create .cache 
      run: | 
        echo "{
          "access_token": "${{ secrets.ACCESS_TOKEN }}",
          "token_type": "Bearer", 
          "expires_in": 3600, 
          "scope": "playlist-modify-public",
          "expires_at": 1716450762,
          "refresh_token": "${{ secrets.REFRESH_TOKEN }}"
        }" >> .cache
    - name: List files
      run: ls
    - name: Execute python script
      run: python3 main.py
      env: 
        SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
        SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
        SPOTIFY_USER: ${{ secrets.SPOTIFY_USER }}
        DISCOVER_WEEKLY_ID: ${{ secrets.DISCOVER_WEEKLY_ID }}
